// Sample customer data
export const customers = [
    {
        eventName: "Will the Jaguars win Super Bowl 2025?",
        username: "Stefan",
        price: 420,
        laterTime: 52,
        isBet: false,
        isSold: false,
        count: 235,
        avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
        toAvatar: "https://docs.material-tailwind.com/img/face-1.jpg",
        position: 50,
        volume: 30,
        address: 0x11111111111111,
        yes: 30,
        no: 70
    },
    {
        eventName: "Will the Jaguars win Super Bowl 2025?",
        username: "Alexa Liras",
        laterTime: 52,
        price: 340,
        isBet: true,
        isSold: false,
        count: 235,
        avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
        toAvatar: "https://docs.material-tailwind.com/img/face-1.jpg",
        position: 50,
        volume: 30,
        address: 0x22222222222,
        yes: 30,
        no: 70
    },
    {
        username: "Richard Gran",
        laterTime: 52,
        price: 520,
        isBet: false,
        isSold: true,
        count: 235,
        avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
        toAvatar: "https://docs.material-tailwind.com/img/face-1.jpg",
        position: 50,
        volume: 30,
        address: 0x3333333,
        yes: 30,
        no: 70
    },
    {
        eventName: "Will the Jaguars win Super Bowl 2025?",
        username: "Micheal Levi",
        laterTime: 54,
        price: 780,
        isBet: true,
        isSold: false,
        count: 235,
        avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
        toAvatar: "https://docs.material-tailwind.com/img/face-1.jpg",
        position: 50,
        volume: 30,
        address: 0x444444444,
        yes: 30,
        no: 70
    },
];
