// Sample customer data
export const customers = [
    {
        eventName: "Confirmed case of monkeypox in US by Aug 31?",
        username: "Stefan",
        price: 420,
        laterTime: 3,
        isBet: false,
        isSold: false,
        count: 235,
        avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
        toAvatar: "https://docs.material-tailwind.com/img/face-1.jpg",
        position: 50,
        volume: 30,
        address: 0x11111111111111,
        yes: 30,
        no: 70,
        totalPrice:90,
        avgPrice:90,
        curPrice:89,
        rate:20
    },
    {
        eventName: "Monkeypox lab leak confirmed by US in 2024?",
        username: "Alexa",
        laterTime: 1,
        price: 340,
        isBet: true,
        isSold: false,
        count: 235,
        avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
        toAvatar: "https://docs.material-tailwind.com/img/face-1.jpg",
        position: 50,
        volume: 30,
        address: 0x22222222222,
        yes: 30,
        no: 70,
        totalPrice:90,
        avgPrice:90,
        curPrice:89,
        rate:30
    },
    {
        eventName: "Georgia Presidential Election Winner",
        username: "Richard",
        laterTime: 5,
        price: 520,
        isBet: false,
        isSold: true,
        count: 235,
        avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
        toAvatar: "https://docs.material-tailwind.com/img/face-1.jpg",
        position: 50,
        volume: 30,
        address: 0x3333333,
        yes: 30,
        no: 70,
        totalPrice:4,
        avgPrice:90,
        curPrice:89,
        rate:30
    },
    {
        eventName: "Will the Jaguars win Super Bowl 2025?",
        username: "Tony",
        laterTime: 1,
        price: 780,
        isBet: true,
        isSold: false,
        count: 235,
        avatar: "https://docs.material-tailwind.com/img/face-2.jpg",
        toAvatar: "https://docs.material-tailwind.com/img/face-1.jpg",
        position: 50,
        volume: 30,
        address: 0x444444444,
        yes: 30,
        no: 70,
        totalPrice:912,
        avgPrice:90,
        curPrice:89,
        rate:30
    },
];
